networks:
  wordpress:

volumes:
  caddy_data:
  caddy_config:

services:
  site:
    container_name: caddy
    image: caddy:alpine
    restart: unless-stopped
    depends_on:
      - "php"
      - "mysql"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./site:/var/www/html
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      wordpress:
        aliases:
          - wp.local
    extra_hosts:
      - "wp.local:127.0.0.1"

  mysql:
    image: docker.io/library/mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  php:
    container_name: php
    userns_mode: keep-id
    user: wp
    group_add:
      - wp
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./site:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - wordpress

  wp:
    container_name: cli
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./site:/var/www/html
    entrypoint: ["wp", "--allow-root"]
