networks:
  wordpress:

services:
  site:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - php
      - mysql
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./site:/var/www/html
    networks:
      - wordpress

  mysql:
    image: docker.io/library/mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  php:
    container_name: php
    userns_mode: keep-id
    user: wp
    group_add:
      - wp
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./site:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - wordpress

  wp:
    container_name: cli
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./site:/var/www/html
    entrypoint: ["wp", "--allow-root"]
